apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2_deployment
  labels:
    app: apache2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2 container
        image: ushajun/capstone2:latest
        ports:
        - containerPort: 80
